CREATE DATABASE IF NOT EXISTS `inf0_sec` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE inf0_sec;

DROP TABLE user;
DROP TABLE comments;
DROP TABLE messages;

CREATE TABLE  `user` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`full_name` VARCHAR( 100 ) NOT NULL ,
`nickname` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL ,
`password` VARCHAR( 100 ) NOT NULL 
) ENGINE = INNODB;

CREATE TABLE  `comments` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`content` VARCHAR( 255 ) NOT NULL ,
`author_id` INT NOT NULL ,
`is_avis` BOOLEAN NOT NULL 
) ENGINE = INNODB;

CREATE TABLE  `messages` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`subject` VARCHAR (100) NOT NULL ,
`content` VARCHAR( 255 ) NOT NULL ,
 `email` VARCHAR (100) NOT NULL 
) ENGINE = INNODB;